import fs from "node:fs";
import path from "node:path";
import { assertValidCurriculum } from "../../src/modules/curriculum/loader";

const documents = assertValidCurriculum();
const output = `// This file is generated by scripts/content/generate-manifest.ts. Do not edit manually.\nimport type { CurriculumDocument } from "@/modules/curriculum/schema";\n\nexport const contentManifest = ${JSON.stringify(
  documents,
  null,
  2,
)} as const satisfies readonly CurriculumDocument[];\n`;
const destination = path.join(process.cwd(), "src", "generated", "content-manifest.ts");

if (process.argv.includes("--check")) {
  const current = fs.existsSync(destination) ? fs.readFileSync(destination, "utf8") : "";
  if (current !== output) {
    throw new Error(
      "src/generated/content-manifest.ts is stale. Run pnpm exec tsx scripts/content/generate-manifest.ts.",
    );
  }
  console.log(`Content manifest is current (${documents.length} documents).`);
  process.exit(0);
}

fs.mkdirSync(path.dirname(destination), { recursive: true });
fs.writeFileSync(destination, output);
console.log(`Generated ${path.relative(process.cwd(), destination)} with ${documents.length} documents.`);
