export const deckCopy = {
  es: {
    ui: {
      deck: "Presentación de Iquiti",
      location: "Centro de Innovación · Ciudad de México",
      language: "Cambiar a inglés",
      overview: "Índice",
      overviewAria: "Ver índice de diapositivas",
      overviewNav: "Ir a una diapositiva",
      pillarNav: "Explorar las cinco partes de Iquiti",
      slide: "diapositiva",
      of: "de",
      previous: "Diapositiva anterior",
      next: "Diapositiva siguiente",
    },
    slides: [
      { label: "Inicio", title: "El hub de innovación de la Ciudad de México." },
      { label: "El problema", title: "El talento está aquí. El camino para crear con tecnología está fragmentado." },
      { label: "La tesis", title: "Educación, innovación y emprendimiento. Un ciclo regenerativo." },
      { label: "El Hub", title: "Un ecosistema, cinco motores." },
      { label: "01 · Academia", title: "Una escuela que enseña a aprender." },
      { label: "02 · Coworking", title: "Un tercer espacio para construir soluciones a los problemas de aquí." },
      { label: "03 · Grants y empleo", title: "Grants para problemas locales. Rutas claras hacia el empleo." },
      { label: "04 · Residencias", title: "Residencias: un puente a mercados globales." },
      { label: "05 · Comunidad", title: "Ya hemos hecho algo así." },
      { label: "El espacio", title: "Un lugar que empieza con la sensación de que todo es posible." },
      { label: "Presupuesto", title: "US$50,000 para ponerlo en marcha." },
      { label: "Plan y metas", title: "Dos formas de aprender. Un hub de largo plazo." },
      { label: "Cierre", title: "Tejamos lo que sigue." },
    ],
    cover: {
      eyebrow: "Iquiti · Centro de Innovación y Academia de Tecnología",
      title: "El hub de innovación de la",
      emphasis: "Ciudad de México.",
      lead: "La próxima empresa puede nacer aquí.",
    },
    problem: {
      category: "El problema", title: "El talento está aquí. El camino para crear con tecnología está fragmentado.",
      points: [
        { title: "La brecha técnica crece", body: "La adopción digital avanza despacio y faltan rutas accesibles para aprender tecnología e IA." },
        { title: "El salto de las ideas al impacto", body: "La débil conexión entre nuestra comunidad y las rutas hacia el conocimiento, el empleo y las oportunidades sofoca la innovación y la creatividad antes de que puedan florecer." },
        { title: "Falta un lugar para soñar en grande", body: "Los sistemas y la cultura actuales limitan qué problemas resolvemos y nuestra capacidad de participar con autonomía en los mercados globales." },
        { title: "El valor se va", body: "Cuando el talento destacado migra, capital, riqueza, conocimiento y cultura crecen fuera. Los empleados de empresas extranjeras a menudo no participan del mayor valor económico que ayudan a crear." },
      ],
      bottom: "El resultado: ideas sin una ruta clara hacia empleo, empresas y reinversión local.",
    },
    thesis: {
      category: "Oportunidad y tesis", title: "Educación, innovación y emprendimiento. Un ciclo regenerativo.",
      statement: "Una escuela abierta y un hub en el mismo lugar convierten capacidad técnica en proyectos, trabajo y empresas nacidas en México.",
      points: [
        { title: "Escuela abierta", body: "Gratuita, autodidacta y entre pares; currículo de código abierto y una primera cohorte presencial de 150 personas durante 12 semanas." },
        { title: "Hub de innovación", body: "Coworking, retos, residencias y eventos donde aplicar lo aprendido y colaborar con emprendedores." },
      ],
    },
    hub: {
      category: "Hub de Innovación", title: "Un ecosistema, cinco motores.",
      pillars: [
        { title: "Academia", body: "Escuela gratuita y de código abierto, con aprendizaje entre pares y proyectos semanales." },
        { title: "Coworking", body: "Un hogar gratuito para emprendedores seleccionados y egresados." },
        { title: "Grants y empleo", body: "Retos locales y una ruta hacia prácticas, co-ops y empleo con empresas seleccionadas." },
        { title: "Residencias", body: "Emprendedores de otras ciudades y países que comparten métodos y perspectivas sobre mercados globales." },
        { title: "Comunidad", body: "Una comunidad de 5,000 personas que conecta talento, emprendedores y aliados mediante encuentros y talleres." },
      ],
    },
    academy: {
      title: "Una escuela que enseña a aprender.",
      promise: "Gratuita. Código abierto. Presencial y en línea.", distinction: "Entre pares, sin clases magistrales.",
      points: [
        { title: "Currículo de código abierto", body: "Una ruta autodidacta con recursos y metas claras que cualquiera puede seguir y adaptar." },
        { title: "Aprendizaje entre pares", body: "Estudiantes aprenden entre sí, resuelven problemas juntos y revisan los proyectos de sus pares." },
        { title: "Aprender con proyectos", body: "Proyectos reales dan práctica para crear empresas. La retroalimentación semanal forma un portafolio para prácticas, co-ops, empleo o proyectos en el hub." },
        { title: "Mentores voluntarios", body: "Planeamos reunir a 10–20 mentores voluntarios que dediquen unas horas semanales a consultas sobre métodos para resolver problemas y autonomía, no contenidos aislados." },
      ],
      bottom: "150 estudiantes presenciales durante 12 semanas. En línea, hasta 5,000 personas a su propio ritmo.",
    },
    coworking: {
      title: "Un tercer espacio para construir soluciones a los problemas de aquí.",
      entry: { title: "Acceso gratuito", body: "Egresados y emprendedores locales pueden solicitar un espacio de trabajo en Iquiti para desarrollar sus proyectos." },
      next: { title: "Continuidad para crear", body: "Equipos encuentran pares y retroalimentación para convertir prototipos en empresas que respondan a necesidades locales." },
      bottom: "La academia abre la puerta; el coworking ofrece el siguiente lugar para construir.",
    },
    grants: {
      title: "Grants para problemas locales. Rutas claras hacia el empleo.",
      need: { title: "Grants para problemas locales", body: "Negocios y organizaciones identifican problemas para que estudiantes y emprendedores desarrollen soluciones.", note: "Capital sujeto a acuerdos con financiadores." },
      teams: { title: "Startups y empleo", body: "Egresados pueden fundar sus propias startups. Emprendedores del hub pueden contratarlos; empresas aliadas pueden ofrecer prácticas, co-ops y puestos de ingeniería.", note: "Las alianzas y contrataciones dependen de acuerdos con cada empresa." },
      bottom: "Tres caminos para egresados: resolver problemas locales, fundar una startup o sumarse a un equipo.",
    },
    residencies: {
      title: "Residencias: un puente a mercados globales.",
      invited: { title: "Fundadores invitados", body: "Emprendedores visitantes de otras ciudades y países llegan a Iquiti para compartir cómo detectan oportunidades y crean para mercados globales." },
      exchange: { title: "Intercambio cultural e intelectual", body: "Los fundadores visitantes dan charlas a nuestra comunidad. Compartir el mismo espacio puede cambiar cómo pensamos, soñamos y vemos el mundo." },
      bottom: "Emprendedores exitosos que visitan la Ciudad de México comparten su experiencia con nuestra comunidad a cambio de espacio de coworking y acceso al hub.",
    },
    events: {
      title: "Ya hemos hecho algo así.",
      community: "miembros de AI Builders México",
      cadence: "Decenas de talleres gratuitos en México y encuentros mensuales que podemos llevar a Utopías.",
      trainingLabel: "Formación corporativa en IA",
      trainingBody: "Hemos ayudado a equipos de estas empresas a usar IA y construir productos.",
      residencyLabel: "Residencia de IA de AI Builders México",
      residencyResults: [
        { value: "10", label: "fundadores acompañados" },
        { value: "8", label: "lanzaron negocios" },
        { value: "5", label: "monetizaron en 3 semanas" },
      ],
      residencyMentors: { value: "6", label: "mentores globales" },
      partnerLabel: "Red para eventos en Utopías",
      peopleLabel: "Historias por integrar",
      people: [
        { name: "Bernardo", detail: "Su historia y papel en el proyecto, por definir." },
        { name: "Luisa", detail: "Su historia y papel en el proyecto, por definir." },
      ],
    },
    space: {
      category: "El espacio", title: "Un lugar que empieza con la sensación de que todo es posible.",
      statement: "Un espacio que invite al asombro, al intercambio y a crear algo más grande que cualquier persona, empresa o misión. Queremos recordarte cada día que todo es posible.",
      images: [
        { src: "/deck/space-coworking.avif", caption: "Trabajo compartido", alt: "Referencia conceptual de mesas de coworking y gradas" },
        { src: "/deck/space-projects.avif", caption: "Aprendizaje entre pares", alt: "Referencia conceptual de grupos trabajando en mesas de proyecto" },
        { src: "/deck/space-events.avif", caption: "Encuentros y talleres", alt: "Referencia conceptual de un espacio abierto para charlas y talleres" },
      ],
      note: "Referencias conceptuales; diseño final por definir.",
    },
    budget: {
      category: "Presupuesto de lanzamiento", title: "US$50,000 para ponerlo en marcha.",
      intro: "Propuesta de honorarios para el equipo mexicano que está creando el currículo, la identidad, el espacio y la operación inicial.",
      areas: ["Currículo y plataforma", "Marca, web y diseño espacial", "Operación de cohorte y comunidad", "Producción y seguimiento"],
      note: "Áreas de inversión propuestas. Obra, mobiliario y capital para grants requieren acuerdos o recursos adicionales.",
    },
    plan: {
      category: "Plan y metas", title: "Dos formas de aprender. Un hub de largo plazo.",
      school: {
        label: "Academia · dos modalidades",
        inPerson: { label: "Presencial", value: "150", unit: "estudiantes", detail: "12 semanas · sesiones de 4 horas con mentoría." },
        online: { label: "En línea", value: "5,000", unit: "meta máxima de participantes", detail: "A su propio ritmo y con menos mentoría e interacción entre pares." },
      },
      hub: {
        label: "Hub · metas propuestas para 12 meses",
        metrics: [
          { value: "20", label: "equipos activos en coworking" },
          { value: "4", label: "residencias de emprendedores" },
          { value: "4", label: "retos locales" },
          { value: "12", label: "eventos abiertos" },
        ],
        note: "Convocatorias continuas, independientes de la cohorte.",
      },
      milestones: [
        { date: "OCT–DIC 2026", label: "Preparación y convocatoria" },
        { date: "ENE 2027", label: "Apertura del hub y la cohorte" },
        { date: "ABR 2027", label: "Primera muestra de proyectos" },
        { date: "CONTINUO", label: "Coworking, residencias, retos y eventos" },
      ],
      note: "Metas indicativas, sujetas a capacidad del espacio, equipo y financiamiento de grants.",
    },
    close: {
      eyebrow: "Iquiti · Coyoacán, Ciudad de México",
      title: "Tejamos", emphasis: "lo que sigue.",
      lead: "Iquiti significa «tejer» en náhuatl. Conectamos escuela, hub y comunidad para que el talento cree proyectos, empleos y empresas desde México para el mundo.",
    },
  },
  en: {
    ui: {
      deck: "Iquiti presentation",
      location: "Innovation Hub · Mexico City",
      language: "Switch to Spanish",
      overview: "Overview",
      overviewAria: "Show slide overview",
      overviewNav: "Go to a slide",
      pillarNav: "Explore Iquiti's five parts",
      slide: "slide",
      of: "of",
      previous: "Previous slide",
      next: "Next slide",
    },
    slides: [
      { label: "Opening", title: "Mexico City's innovation hub." },
      { label: "The problem", title: "The talent is here. The path to building with technology is fragmented." },
      { label: "Our thesis", title: "Education, innovation, entrepreneurship. One regenerative cycle." },
      { label: "The Hub", title: "One ecosystem, five engines." },
      { label: "01 · Academy", title: "A school that teaches how to learn." },
      { label: "02 · Coworking", title: "A third space to build solutions for the problems next door." },
      { label: "03 · Grants & employment", title: "Grants for local problems. Clear paths into employment." },
      { label: "04 · Residencies", title: "Residencies: a bridge to global markets." },
      { label: "05 · Community", title: "We've done something like this before." },
      { label: "The space", title: "A place that starts with a feeling that anything is possible." },
      { label: "Budget", title: "US$50,000 to launch it." },
      { label: "Plan & targets", title: "Two ways to learn. One hub built to last." },
      { label: "Closing", title: "Let's weave what comes next." },
    ],
    cover: {
      eyebrow: "Iquiti · Innovation Hub and Technology Academy",
      title: "Mexico City's",
      emphasis: "innovation hub.",
      lead: "The next company could start here.",
    },
    problem: {
      category: "The problem", title: "The talent is here. The path to building with technology is fragmented.",
      points: [
        { title: "The technical skills gap widens", body: "Digital adoption moves slowly, and accessible paths to learn technology and AI remain limited." },
        { title: "The leap from ideas to impact", body: "Weak connectivity between our community and pathways to knowledge, employment, and opportunity kills innovation and creativity before they have a chance to flourish." },
        { title: "No place to dream bigger", body: "Established systems and culture narrow which problems we solve and limit our ability to participate in global markets on our own terms." },
        { title: "Value flows elsewhere", body: "When top talent leaves, capital, wealth, knowledge, and culture grow elsewhere. Employees of foreign companies often lack participation in significant economic upside." },
      ],
      bottom: "The result: ideas without a clear path to jobs, companies, or local reinvestment.",
    },
    thesis: {
      category: "Opportunity & thesis", title: "Education, innovation, entrepreneurship. One regenerative cycle.",
      statement: "An open school and a hub in one place turn technical ability into projects, careers, and companies rooted in Mexico.",
      points: [
        { title: "Open school", body: "Free, self-directed, and peer-led; an open-source curriculum and a first in-person cohort of 150 people over 12 weeks." },
        { title: "Innovation hub", body: "Coworking, challenges, residencies, and events where learners apply their skills alongside entrepreneurs." },
      ],
    },
    hub: {
      category: "Innovation Hub", title: "One ecosystem, five engines.",
      pillars: [
        { title: "Academy", body: "A free, open-source school built around peer learning and weekly projects." },
        { title: "Coworking", body: "A free home for selected entrepreneurs and graduates." },
        { title: "Grants & employment", body: "Local challenges and paths to internships, co-ops, and jobs with selected companies." },
        { title: "Residencies", body: "Entrepreneurs from other cities and countries who share methods and perspectives on global markets." },
        { title: "Community", body: "A community of 5,000 connecting talent, founders, and partners through gatherings and workshops." },
      ],
    },
    academy: {
      title: "A school that teaches how to learn.",
      promise: "Free. Open source. In person and online.", distinction: "Peer-led, with no lectures.",
      points: [
        { title: "Open-source curriculum", body: "A self-directed roadmap with resources and clear milestones anyone can follow and adapt." },
        { title: "Peer-to-peer learning", body: "Learners teach one another, solve problems together, and review their peers' projects." },
        { title: "Project-based practice", body: "Real-world projects give students the practice needed to build companies. Weekly feedback builds a portfolio for internships, co-ops, jobs, or hub projects." },
        { title: "Volunteer mentors", body: "We plan for 10–20 volunteer mentors to set aside a few hours each week for office hours on problem-solving methods and self-reliance, not isolated facts." },
      ],
      bottom: "150 in-person students over 12 weeks. Online, up to 5,000 people learning at their own pace.",
    },
    coworking: {
      title: "A third space to build solutions for the problems next door.",
      entry: { title: "Free access", body: "Graduates and local entrepreneurs can apply for workspace at Iquiti to develop their projects." },
      next: { title: "Room to keep building", body: "Teams find peers and feedback to turn prototypes into companies that address local needs." },
      bottom: "The Academy opens the door; coworking offers the next place to build.",
    },
    grants: {
      title: "Grants for local problems. Clear paths into employment.",
      need: { title: "Grants for local problems", body: "Businesses and organizations identify problems for students and entrepreneurs to solve.", note: "Capital depends on funding agreements." },
      teams: { title: "Startups and employment", body: "Graduates can launch their own startups. Entrepreneurs in the hub can hire them; selected partner companies can offer internships, co-ops, and engineering roles.", note: "Partnerships and hiring depend on agreements with each company." },
      bottom: "Three paths for graduates: solve a local problem, launch a startup, or join a team.",
    },
    residencies: {
      title: "Residencies: a bridge to global markets.",
      invited: { title: "Invited founders", body: "Visiting entrepreneurs from other cities and countries join Iquiti to share how they spot opportunities and build for global markets." },
      exchange: { title: "Cultural and intellectual exchange", body: "Visiting founders give talks to our community. Sharing the same room can shift how we think, dream, and see the world." },
      bottom: "Successful entrepreneurs visiting Mexico City share their experience with our community in exchange for coworking space and access to the hub.",
    },
    events: {
      title: "We've done something like this before.",
      community: "AI Builders México members",
      cadence: "Dozens of free workshops across Mexico, plus monthly gatherings we can bring to Utopías.",
      trainingLabel: "Corporate AI workshops",
      trainingBody: "We've helped teams at these companies learn to use AI and build products.",
      residencyLabel: "AI Builders México AI Residency",
      residencyResults: [
        { value: "10", label: "founders supported" },
        { value: "8", label: "launched businesses" },
        { value: "5", label: "monetized by week 3" },
      ],
      residencyMentors: { value: "6", label: "global mentors" },
      partnerLabel: "Network for Utopías events",
      peopleLabel: "Stories to add",
      people: [
        { name: "Bernardo", detail: "Story and role in the project to be defined." },
        { name: "Luisa", detail: "Story and role in the project to be defined." },
      ],
    },
    space: {
      category: "The space", title: "A place that starts with a feeling that anything is possible.",
      statement: "A space that invites wonder, exchange, and the creation of something bigger than any one person, company, or mission. We want to remind you every day that anything is possible.",
      images: [
        { src: "/deck/space-coworking.avif", caption: "Shared workspace", alt: "Concept reference of coworking tables and stepped seating" },
        { src: "/deck/space-projects.avif", caption: "Peer learning", alt: "Concept reference of groups working around project tables" },
        { src: "/deck/space-events.avif", caption: "Gatherings and workshops", alt: "Concept reference of an open space for talks and workshops" },
      ],
      note: "Concept references; final design to be determined.",
    },
    budget: {
      category: "Launch budget", title: "US$50,000 to launch it.",
      intro: "Proposed compensation for the Mexican team creating the curriculum, identity, space, and initial operations.",
      areas: ["Curriculum and platform", "Brand, website, and space design", "Cohort and community operations", "Production and measurement"],
      note: "Proposed uses of funds. Construction, furniture, and grant capital require additional agreements or resources.",
    },
    plan: {
      category: "Plan & targets", title: "Two ways to learn. One hub built to last.",
      school: {
        label: "Academy · two formats",
        inPerson: { label: "In person", value: "150", unit: "students", detail: "12 weeks · four-hour sessions with mentorship." },
        online: { label: "Online", value: "5,000", unit: "maximum learner target", detail: "Self-paced, with less mentorship and peer interaction." },
      },
      hub: {
        label: "Hub · proposed 12-month targets",
        metrics: [
          { value: "20", label: "active coworking teams" },
          { value: "4", label: "entrepreneur residencies" },
          { value: "4", label: "local challenges" },
          { value: "12", label: "open events" },
        ],
        note: "Rolling applications, independent of the cohort.",
      },
      milestones: [
        { date: "OCT–DEC 2026", label: "Prepare and recruit" },
        { date: "JAN 2027", label: "Open the hub and cohort" },
        { date: "APR 2027", label: "First project showcase" },
        { date: "ONGOING", label: "Coworking, residencies, challenges, events" },
      ],
      note: "Indicative targets, subject to space capacity, staffing, and grant funding.",
    },
    close: {
      eyebrow: "Iquiti · Coyoacán, Mexico City",
      title: "Let's weave", emphasis: "what comes next.",
      lead: "Iquiti means “to weave” in Nahuatl. We connect school, hub, and community so talent can build projects, careers, and companies from Mexico for the world.",
    },
  },
} as const;

export type DeckLanguage = keyof typeof deckCopy;
