export const deckCopy = {
  es: {
    ui: {
      deck: "Presentación de Iquiti",
      location: "Instituto del Emprendedor · Ciudad de México",
      language: "Cambiar a inglés",
      overview: "Índice",
      overviewAria: "Ver índice de diapositivas",
      overviewNav: "Ir a una diapositiva",
      pillarNav: "Explorar las cinco partes de Iquiti",
      slide: "diapositiva",
      of: "de",
      previous: "Diapositiva anterior",
      next: "Diapositiva siguiente",
    },
    slides: [
      { label: "Inicio", title: "El hub de innovación de la Ciudad de México." },
      { label: "El problema", title: "El talento está aquí. El camino para crear con tecnología está fragmentado." },
      { label: "Oportunidad y tesis", title: "Educación, innovación y emprendimiento. Un ciclo regenerativo." },
      { label: "Solución", title: "Un ecosistema, cinco motores." },
      { label: "01 · Academia", title: "Una escuela que enseña a aprender." },
      { label: "02 · Coworking", title: "Un tercer espacio para construir soluciones a los problemas de aquí." },
      { label: "03 · Fondos a la innovación y empleo", title: "Fondos a la innovación para problemas locales. Rutas claras hacia el empleo." },
      { label: "04 · Residencias", title: "Residencias: un puente a mercados globales." },
      { label: "05 · Comunidad", title: "Ya hemos hecho algo así." },
      { label: "El espacio", title: "Un lugar que empieza con la sensación de que todo es posible." },
      { label: "Presupuesto de lanzamiento", title: "Dónde va el financiamiento." },
      { label: "Plan y metas", title: "Dos formas de aprender. Un hub de largo plazo." },
      { label: "Cierre", title: "Aquí empieza el tejido." },
    ],
    cover: {
      eyebrow: "Instituto del Emprendedor",
      title: "El hub de\ninnovación de la",
      emphasis: "Ciudad de México.",
      lead: "Coworking, comunidad y un currículo open source con mentoría para construir empresas en México.",
    },
    problem: {
      category: "El problema", title: "El talento está aquí. El camino para crear con tecnología está fragmentado.",
      points: [
        { title: "La brecha técnica crece", body: "Hay talento, pero las metodologías para enseñar tecnología e IA son deficientes: teóricas, lentas y desconectadas de construir de verdad." },
        { title: "Las ideas no llegan a producto", body: "No hay un sistema claro de idea a producto. El proceso se corta en formación, prototipos o intención, sin llegar a mercado." },
        { title: "Mercados locales sin productos propios", body: "Faltan apps y servicios locales de calidad. Con el talento que ya está aquí, México podría tener su propio Thumbtack, Platzi o marketplace, hechos para resolver problemas de aquí." },
        { title: "Los mercados globales se llevan el talento", body: "Hoy aportamos afuera casi solo con personas, no con productos ni empresas. Eso tiene que cambiar: crear desde México para competir en lo global, no solo abastecer de talento." },
      ],
      cycleAlt: "El resultado: un ciclo roto. Talento sin empresas. Empresas sin capital. Capital que no regresa.",
    },
    thesis: {
      category: "Oportunidad y tesis", title: "Educación, innovación y emprendimiento. Un ciclo regenerativo.",
      statement: "Una escuela abierta y un hub en el mismo lugar convierten capacidad técnica en proyectos, trabajo y empresas nacidas en México.",
      points: [
        { title: "Currículo Open Source", body: "Autodidacta: aprendes con otros estudiantes. Contenido de código abierto. Primer cohort presencial: 150 personas durante 12 semanas." },
        { title: "Hub de innovación", body: "Coworking, retos, residencias y eventos para aplicar lo aprendido junto a emprendedores." },
      ],
      cycleAlt: "El resultado: un ciclo regenerativo. Talento que construye. Empresas que crecen. Capital que regresa.",
    },
    hub: {
      category: "Solución", title: "Un ecosistema, cinco motores.",
      pillars: [
        { title: "Academia", body: "Escuela gratuita y de código abierto, con proyectos semanales y aprendizaje entre estudiantes." },
        { title: "Coworking", body: "Un hogar gratuito para emprendedores seleccionados y egresados." },
        { title: "Fondos a la innovación y empleo", body: "Retos locales y una ruta hacia prácticas profesionales y empleos con empresas aliadas." },
        { title: "Residencias", body: "Emprendedores de otras ciudades y países que comparten métodos y perspectivas sobre mercados globales." },
        { title: "Comunidad", body: "Una comunidad de 5,000 personas que conecta talento, emprendedores y aliados mediante encuentros y talleres." },
      ],
    },
    academy: {
      title: "Una escuela que enseña a aprender.",
      promise: "Gratuita. Código abierto. Presencial y en línea.", distinction: "Aprendes con otros estudiantes, sin clases magistrales.",
      points: [
        { title: "Currículo de código abierto", body: "Una ruta autodidacta con recursos y metas claras que cualquiera puede seguir y adaptar, inspirada en las escuelas 42 y The Odin Project." },
        { title: "Aprendizaje entre estudiantes", body: "Estudiantes aprenden entre sí, resuelven problemas juntos y revisan los proyectos de otros." },
        { title: "Aprender con proyectos", body: "Proyectos reales dan práctica para crear empresas. La retroalimentación semanal forma un portafolio para prácticas, co-ops (cooperativas), empleo o proyectos en el hub." },
        { title: "Mentores voluntarios", body: "Planeamos reunir a 10–20 mentores voluntarios que dediquen unas horas semanales a consultas sobre métodos para resolver problemas y autonomía, no contenidos aislados." },
      ],
      bottom: "150 estudiantes presenciales durante 12 semanas. En línea, hasta 5,000 personas a su propio ritmo.",
    },
    coworking: {
      title: "Un tercer espacio para construir soluciones a los problemas de aquí.",
      entry: { title: "Acceso gratuito", body: "Egresados y emprendedores locales pueden solicitar un espacio de trabajo en Iquiti para desarrollar sus proyectos." },
      next: { title: "Continuidad para crear", body: "Equipos encuentran pares y retroalimentación para convertir prototipos en empresas que respondan a necesidades locales." },
      bottom: "La academia abre la puerta; el coworking ofrece el siguiente lugar para construir.",
    },
    grants: {
      title: "Fondos a la innovación para problemas locales. Rutas claras hacia el empleo.",
      need: { title: "Fondos a la innovación para problemas locales", body: "Negocios y organizaciones identifican problemas para que estudiantes y emprendedores desarrollen soluciones.", note: "Capital sujeto a acuerdos con financiadores." },
      teams: { title: "Startups y empleo", body: "Egresados pueden fundar sus propias startups. Emprendedores del hub pueden contratarlos; empresas aliadas pueden ofrecer prácticas, co-ops (cooperativas) y puestos de ingeniería.", note: "Las alianzas y contrataciones dependen de acuerdos con cada empresa." },
      bottom: "Tres caminos para egresados: resolver problemas locales, fundar una startup o sumarse a un equipo.",
    },
    residencies: {
      title: "Residencias: un puente a mercados globales.",
      invited: { title: "Fundadores invitados", body: "Emprendedores visitantes de otras ciudades y países llegan a Iquiti para compartir cómo detectan oportunidades y crean para mercados globales." },
      exchange: { title: "Intercambio cultural e intelectual", body: "Los fundadores visitantes dan charlas a nuestra comunidad. Compartir el mismo espacio puede cambiar cómo pensamos, soñamos y vemos el mundo." },
      bottom: "Emprendedores exitosos que visitan la Ciudad de México comparten su experiencia con nuestra comunidad a cambio de espacio de coworking y acceso al hub.",
    },
    events: {
      title: "Ya hemos hecho algo así.",
      community: "miembros de AI Builders México",
      cadence: "Decenas de talleres gratuitos en México y encuentros mensuales que podemos llevar a Utopías.",
      residencyLabel: "Residencia de IA de AI Builders México",
      residencyResults: [
        { value: "10", label: "seleccionados entre 300 postulaciones" },
        { value: "8", label: "lanzaron negocios" },
        { value: "4", label: "monetizaron en 3 semanas" },
      ],
      residencyMentors: { value: "7", label: "mentores internacionales" },
      partnerLabel: "Red para eventos en Utopías",
      gallery: [
        { src: "/deck/community/community-group.png", alt: "Integrantes de la comunidad reunidos en un encuentro" },
        { src: "/deck/community/community-founders.png", alt: "Tres participantes posan durante un evento de la comunidad" },
        { src: "/deck/community/community-audience.png", alt: "Participantes escuchan una charla en un encuentro" },
        { src: "/deck/community/community-exchange.png", alt: "Una participante comparte un momento con otros miembros de la comunidad" },
      ],
    },
    space: {
      category: "El espacio", title: "Un lugar que empieza con la sensación de que todo es posible.",
      statement: "Un espacio que invite al asombro, al intercambio y a crear algo más grande que cualquier persona, empresa o misión. Queremos recordarte cada día que todo es posible.",
      images: [
        { src: "/images/galeria/instituto/visor-1.webp", caption: "Aprender, construir, conectar", alt: "Vista del espacio Iquiti con el lema Aprender Construir Conectar y mesa circular de trabajo" },
        { src: "/images/galeria/comunidad/comunidad-4.webp", caption: "Colaboración", alt: "Dos personas trabajando juntas en una mesa compartida" },
        { src: "/images/galeria/comunidad/comunidad-8.webp", caption: "Encuentros y comunidad", alt: "Comunidad reunida en las gradas del hub" },
      ],
      note: "Concepto del espacio Iquiti, pensado para asombro, intercambio y creación. Referencias conceptuales; diseño final por definir.",
    },
    budget: {
      category: "Presupuesto de lanzamiento", title: "Dónde va el financiamiento.",
      intro: "La operación y la mentoría reciben prioridad dentro de estas áreas de inversión:",
      areas: [
        { title: "Operación (OPEX)", body: "Contratar al equipo, incluido un community manager; mantener el código del currículo y sostener las operaciones diarias." },
        { title: "Estipendios para mentores", body: "Apoyar a la primera cohorte de mentores. Con el tiempo, egresados de la escuela podrán convertirse en mentores." },
        { title: "Currículo y plataforma", body: "Desarrollar la plataforma de aprendizaje y evolucionar el currículo de código abierto." },
        { title: "Marca, web y diseño espacial", body: "Crear la identidad, el sitio web y el diseño del espacio para recibir a la comunidad." },
        { title: "Operación de cohorte y comunidad", body: "Convocar y acompañar a la cohorte presencial y organizar la comunidad." },
        { title: "Producción y seguimiento", body: "Producir talleres y encuentros, y medir los resultados del programa." },
      ],
      note: "Obra, mobiliario y capital destinado a fondos a la innovación requieren acuerdos o recursos adicionales.",
    },
    plan: {
      category: "Plan y metas", title: "Dos formas de aprender. Un hub de largo plazo.",
      school: {
        label: "Academia · dos modalidades",
        inPerson: { label: "Presencial", value: "150", unit: "estudiantes", detail: "12 semanas · sesiones de 4 horas con mentoría." },
        online: { label: "En línea", value: "5,000", unit: "meta máxima de participantes", detail: "A su propio ritmo y con menos mentoría e interacción entre estudiantes." },
      },
      hub: {
        label: "Hub · metas propuestas para 12 meses",
        metrics: [
          { value: "20", label: "equipos activos en coworking" },
          { value: "4", label: "residencias de emprendedores" },
          { value: "4", label: "retos locales" },
          { value: "12", label: "eventos abiertos" },
        ],
        note: "Convocatorias continuas, independientes de la cohorte.",
      },
      milestones: [
        { date: "OCT–DIC 2026", label: "Preparación y convocatoria" },
        { date: "ENE 2027", label: "Apertura del hub y la cohorte" },
        { date: "ABR 2027", label: "Primera muestra de proyectos" },
        { date: "CONTINUO", label: "Coworking, residencias, retos y eventos" },
      ],
      note: "Metas indicativas, sujetas a capacidad del espacio, equipo y financiamiento de los retos locales.",
    },
    close: {
      eyebrow: "Coyoacán, Ciudad de México",
      title: "Aquí empieza", emphasis: "el tejido.",
      lead: "Iquiti significa «tejer» en náhuatl. Conectamos educación, hub y comunidad para que el talento cree proyectos, empleos y empresas desde México para el mundo.",
    },
  },
  en: {
    ui: {
      deck: "Iquiti presentation",
      location: "Instituto del Emprendedor · Mexico City",
      language: "Switch to Spanish",
      overview: "Overview",
      overviewAria: "Show slide overview",
      overviewNav: "Go to a slide",
      pillarNav: "Explore Iquiti's five parts",
      slide: "slide",
      of: "of",
      previous: "Previous slide",
      next: "Next slide",
    },
    slides: [
      { label: "Opening", title: "Mexico City's innovation hub." },
      { label: "The problem", title: "The talent is here. The path to building with technology is fragmented." },
      { label: "Opportunity & thesis", title: "Education, innovation, entrepreneurship. One regenerative cycle." },
      { label: "Solution", title: "One ecosystem, five engines." },
      { label: "01 · Academy", title: "A school that teaches how to learn." },
      { label: "02 · Coworking", title: "A third space to build solutions for the problems next door." },
      { label: "03 · Grants & employment", title: "Grants for local problems. Clear paths into employment." },
      { label: "04 · Residencies", title: "Residencies: a bridge to global markets." },
      { label: "05 · Community", title: "We've done something like this before." },
      { label: "The space", title: "A place that starts with a feeling that anything is possible." },
      { label: "Launch budget", title: "Where the funding goes." },
      { label: "Plan & targets", title: "Two ways to learn. One hub built to last." },
      { label: "Closing", title: "This is where the weave begins." },
    ],
    cover: {
      eyebrow: "Instituto del Emprendedor",
      title: "Mexico City's",
      emphasis: "innovation hub.",
      lead: "Coworking, community, and an open-source curriculum with mentorship to build companies in Mexico.",
    },
    problem: {
      category: "The problem", title: "The talent is here. The path to building with technology is fragmented.",
      points: [
        { title: "The technical skills gap widens", body: "Talent is here, but the methods for teaching technology and AI are weak: theoretical, slow, and disconnected from real building." },
        { title: "Ideas don't become products", body: "There is no clear system from idea to product. The process breaks at training, prototypes, or intention, before reaching market." },
        { title: "Local markets without local products", body: "Quality local apps and services are missing. With the talent already here, Mexico could have its own Thumbtack, Platzi, or marketplace, built to solve problems here." },
        { title: "Global markets take the talent", body: "Today we contribute abroad mostly with people, not products or companies. That has to change: build from Mexico to compete globally, not only supply talent." },
      ],
      cycleAlt: "The result: a broken cycle. Talent without companies. Companies without capital. Capital that doesn't return.",
    },
    thesis: {
      category: "Opportunity & thesis", title: "Education, innovation, entrepreneurship. One regenerative cycle.",
      statement: "An open school and a hub in one place turn technical ability into projects, careers, and companies rooted in Mexico.",
      points: [
        { title: "Open Source Curriculum", body: "Self-directed: you learn with other students. Open-source content. First in-person cohort: 150 people over 12 weeks." },
        { title: "Innovation hub", body: "Coworking, challenges, residencies, and events to apply what you've learned alongside entrepreneurs." },
      ],
      cycleAlt: "The result: a regenerative cycle. Talent that builds. Companies that grow. Capital that returns.",
    },
    hub: {
      category: "Solution", title: "One ecosystem, five engines.",
      pillars: [
        { title: "Academy", body: "A free, open-source school with weekly projects and learning among students." },
        { title: "Coworking", body: "A free home for selected entrepreneurs and graduates." },
        { title: "Grants & employment", body: "Local challenges and paths to internships and jobs with partner companies." },
        { title: "Residencies", body: "Entrepreneurs from other cities and countries who share methods and perspectives on global markets." },
        { title: "Community", body: "A community of 5,000 connecting talent, founders, and partners through gatherings and workshops." },
      ],
    },
    academy: {
      title: "A school that teaches how to learn.",
      promise: "Free. Open source. In person and online.", distinction: "You learn with other students, with no lectures.",
      points: [
        { title: "Open-source curriculum", body: "A self-directed roadmap with resources and clear milestones anyone can follow and adapt, modeled on the 42 schools and The Odin Project." },
        { title: "Learning among students", body: "Students learn from one another, solve problems together, and review each other's projects." },
        { title: "Project-based practice", body: "Real-world projects give students the practice needed to build companies. Weekly feedback builds a portfolio for internships, co-ops, jobs, or hub projects." },
        { title: "Volunteer mentors", body: "We plan for 10–20 volunteer mentors to set aside a few hours each week for office hours on problem-solving methods and self-reliance, not isolated facts." },
      ],
      bottom: "150 in-person students over 12 weeks. Online, up to 5,000 people learning at their own pace.",
    },
    coworking: {
      title: "A third space to build solutions for the problems next door.",
      entry: { title: "Free access", body: "Graduates and local entrepreneurs can apply for workspace at Iquiti to develop their projects." },
      next: { title: "Room to keep building", body: "Teams find peers and feedback to turn prototypes into companies that address local needs." },
      bottom: "The Academy opens the door; coworking offers the next place to build.",
    },
    grants: {
      title: "Grants for local problems. Clear paths into employment.",
      need: { title: "Grants for local problems", body: "Businesses and organizations identify problems for students and entrepreneurs to solve.", note: "Capital depends on funding agreements." },
      teams: { title: "Startups and employment", body: "Graduates can launch their own startups. Entrepreneurs in the hub can hire them; selected partner companies can offer internships, co-ops, and engineering roles.", note: "Partnerships and hiring depend on agreements with each company." },
      bottom: "Three paths for graduates: solve a local problem, launch a startup, or join a team.",
    },
    residencies: {
      title: "Residencies: a bridge to global markets.",
      invited: { title: "Invited founders", body: "Visiting entrepreneurs from other cities and countries join Iquiti to share how they spot opportunities and build for global markets." },
      exchange: { title: "Cultural and intellectual exchange", body: "Visiting founders give talks to our community. Sharing the same room can shift how we think, dream, and see the world." },
      bottom: "Successful entrepreneurs visiting Mexico City share their experience with our community in exchange for coworking space and access to the hub.",
    },
    events: {
      title: "We've done this before.",
      community: "AI Builders México members",
      cadence: "Dozens of free workshops across Mexico, plus monthly gatherings we can bring to Utopías.",
      residencyLabel: "AI Builders México AI Residency",
      residencyResults: [
        { value: "10", label: "selected from 300 applications" },
        { value: "8", label: "launched businesses" },
        { value: "4", label: "monetized by week 3" },
      ],
      residencyMentors: { value: "7", label: "international mentors" },
      partnerLabel: "Network for Utopías events",
      gallery: [
        { src: "/deck/community/community-group.png", alt: "Community members gathered at an event" },
        { src: "/deck/community/community-founders.png", alt: "Three participants pose at a community event" },
        { src: "/deck/community/community-audience.png", alt: "Participants listen to a talk at a gathering" },
        { src: "/deck/community/community-exchange.png", alt: "A participant shares a moment with other community members" },
      ],
    },
    space: {
      category: "The space", title: "A place that starts with a feeling that anything is possible.",
      statement: "A space that invites wonder, exchange, and the creation of something bigger than any one person, company, or mission. We want to remind you every day that anything is possible.",
      images: [
        { src: "/images/galeria/instituto/visor-1.webp", caption: "Learn, build, connect", alt: "View of the Iquiti space with the Learn Build Connect motto and circular work table" },
        { src: "/images/galeria/comunidad/comunidad-4.webp", caption: "Collaboration", alt: "Two people working together at a shared table" },
        { src: "/images/galeria/comunidad/comunidad-8.webp", caption: "Gatherings and community", alt: "Community gathered on the hub's stepped seating" },
      ],
      note: "Iquiti space concept—designed for wonder, exchange, and creation. Concept references; final design to be determined.",
    },
    budget: {
      category: "Launch budget", title: "Where the funding goes.",
      intro: "Operations and mentorship lead these funding priorities:",
      areas: [
        { title: "Operations (OPEX)", body: "Staffing and hiring, including a community manager; maintaining the curriculum codebase and running day-to-day operations." },
        { title: "Mentor stipends", body: "Support for the initial mentor cohort. Over time, school graduates can become mentors themselves." },
        { title: "Curriculum and platform", body: "Build the learning platform and keep improving the open-source curriculum." },
        { title: "Brand, website, and space design", body: "Create the identity, website, and space design that welcome the community." },
        { title: "Cohort and community operations", body: "Recruit and support the in-person cohort and organize the community." },
        { title: "Production and measurement", body: "Produce workshops and gatherings, and measure the program's results." },
      ],
      note: "Construction, furniture, and grant capital require additional agreements or resources.",
    },
    plan: {
      category: "Plan & targets", title: "Two ways to learn. One hub built to last.",
      school: {
        label: "Academy · two formats",
        inPerson: { label: "In person", value: "150", unit: "students", detail: "12 weeks · four-hour sessions with mentorship." },
        online: { label: "Online", value: "5,000", unit: "maximum learner target", detail: "Self-paced, with less mentorship and interaction among students." },
      },
      hub: {
        label: "Hub · proposed 12-month targets",
        metrics: [
          { value: "20", label: "active coworking teams" },
          { value: "4", label: "entrepreneur residencies" },
          { value: "4", label: "local challenges" },
          { value: "12", label: "open events" },
        ],
        note: "Rolling applications, independent of the cohort.",
      },
      milestones: [
        { date: "OCT–DEC 2026", label: "Prepare and recruit" },
        { date: "JAN 2027", label: "Open the hub and cohort" },
        { date: "APR 2027", label: "First project showcase" },
        { date: "ONGOING", label: "Coworking, residencies, challenges, events" },
      ],
      note: "Indicative targets, subject to space capacity, staffing, and grant funding.",
    },
    close: {
      eyebrow: "Coyoacán, Mexico City",
      title: "This is where", emphasis: "the weave begins.",
      lead: "Iquiti means “to weave” in Nahuatl. We connect education, hub, and community so talent can build projects, careers, and companies from Mexico for the world.",
    },
  },
} as const;

export type DeckLanguage = keyof typeof deckCopy;
