export const deckCopy = {
  es: {
    ui: {
      deck: "Presentación de Iquiti",
      location: "Centro de Innovación · Ciudad de México",
      language: "Cambiar a inglés",
      overview: "Índice",
      overviewAria: "Ver índice de diapositivas",
      overviewNav: "Ir a una diapositiva",
      pillarNav: "Explorar las cinco partes de Iquiti",
      slide: "diapositiva",
      of: "de",
      previous: "Diapositiva anterior",
      next: "Diapositiva siguiente",
    },
    slides: [
      { label: "Inicio", title: "El hub de innovación de la Ciudad de México." },
      { label: "El problema", title: "El talento está aquí. El camino para crear con tecnología está fragmentado." },
      { label: "Reinversión", title: "Un ciclo que multiplica oportunidades en la Ciudad de México." },
      { label: "La tesis", title: "La innovación empieza cuando más personas pueden crear." },
      { label: "El Hub", title: "Un ecosistema, cinco motores." },
      { label: "01 · Academia", title: "Aprender a aprender. Aprender construyendo." },
      { label: "02 · Coworking", title: "Un lugar para crear empresas en comunidad." },
      { label: "03 · Grants y talento", title: "Retos locales y oportunidades de empleo." },
      { label: "04 · Residencias", title: "Perspectivas globales, trabajo local." },
      { label: "05 · Eventos", title: "Eventos que conectan Utopías con el mundo tecnológico." },
      { label: "El espacio", title: "Que se sienta como una posibilidad nueva." },
      { label: "Presupuesto", title: "US$50,000 para ponerlo en marcha." },
      { label: "Plan y metas", title: "Una primera cohorte. Un hub de largo plazo." },
      { label: "Cierre", title: "Construyamos el siguiente nodo." },
    ],
    cover: {
      eyebrow: "Iquiti · Centro de Innovación y Academia de Tecnología",
      title: "El hub de innovación de la",
      emphasis: "Ciudad de México.",
      lead: "La próxima empresa puede nacer aquí.",
    },
    problem: {
      category: "El problema", title: "El talento está aquí. El camino para crear con tecnología está fragmentado.",
      points: [
        { title: "La brecha de habilidades tecnológicas crece", body: "Mientras la IA multiplica lo que pueden lograr quienes saben usarla, el acceso al aprendizaje y la práctica para construir con ella no avanza al mismo ritmo." },
        { title: "El salto de las ideas al impacto", body: "Ese salto necesita proyectos, pares, espacio físico y apoyo. Sin ellos, las ideas difícilmente se convierten en soluciones útiles o empresas que crecen." },
        { title: "Un lugar para soñar", body: "El talento local necesita un espacio cercano donde fundadores, ideas y culturas del mundo amplíen lo que parece posible." },
      ],
      bottom: "El resultado: ideas sin una ruta clara hacia empleo, empresas y reinversión local.",
    },
    reinvestment: {
      category: "Ciclo de reinversión", title: "Un ciclo que multiplica oportunidades en la Ciudad de México.",
      steps: [
        { title: "Formación abierta", body: "Aprenden a usar IA y tecnología para crear productos y negocios, a su ritmo y con pares." },
        { title: "Proyectos en el hub", body: "El coworking, los retos y emprendedores residentes ayudan a llevar esas habilidades a soluciones reales." },
        { title: "Empleo y empresas", body: "Egresados pueden unirse a empresas del hub o aliadas; los nuevos equipos también pueden contratar localmente." },
        { title: "Reinversión", body: "Empresas que crecen pueden contratar y formar a otros. Un evento de liquidez podría financiar la siguiente generación." },
      ],
      bottom: "Talento, empresas y capital pueden volver al ecosistema de la Ciudad de México, ciclo tras ciclo.",
    },
    thesis: {
      category: "Oportunidad y tesis", title: "La innovación empieza cuando más personas pueden crear.",
      statement: "Una escuela abierta y un hub en el mismo lugar convierten capacidad técnica en proyectos, trabajo y empresas nacidas en Coyoacán.",
      points: [
        { title: "Escuela abierta", body: "Gratuita, autodidacta y entre pares; currículo de código abierto y una primera cohorte presencial de 150 personas durante 12 semanas." },
        { title: "Hub de innovación", body: "Coworking, retos, residencias y eventos donde aplicar lo aprendido y colaborar con emprendedores." },
      ],
    },
    hub: {
      category: "Hub de Innovación", title: "Un ecosistema, cinco motores.",
      pillars: [
        { title: "Academia", body: "Escuela gratuita y de código abierto, con aprendizaje entre pares y proyectos semanales." },
        { title: "Coworking", body: "Un hogar gratuito para emprendedores seleccionados y egresados." },
        { title: "Grants y talento", body: "Retos locales y una ruta hacia prácticas y empleo con empresas del hub y aliados." },
        { title: "Residencias", body: "Emprendedores de otras ciudades y países que llegan a intercambiar conocimiento." },
        { title: "Eventos", body: "Encuentros mensuales y talleres con voces de nuestra red de aliados tecnológicos." },
      ],
    },
    academy: {
      title: "Aprender a aprender. Aprender construyendo.",
      promise: "Gratuita. Código abierto. Presencial y en línea.", distinction: "Entre pares, sin clases magistrales.",
      points: [
        { title: "Método", body: "Aprendizaje autodidacta, resolución de problemas y apoyo entre pares." },
        { title: "Estructura", body: "Currículo abierto, rendición de cuentas y proyectos cada semana." },
        { title: "Siguiente paso", body: "Portafolio para buscar internships, co-ops o trabajo; proyectos que pueden seguir en el hub." },
      ],
      bottom: "Primera cohorte: 150 estudiantes y 12 semanas para construir en comunidad.",
    },
    coworking: {
      title: "Un lugar para crear empresas en comunidad.",
      entry: { title: "Acceso gratuito", body: "Egresados y emprendedores locales pueden solicitar un espacio de trabajo en Iquiti para desarrollar sus proyectos." },
      next: { title: "Continuidad para crear", body: "Equipos encuentran pares y retroalimentación para convertir prototipos en empresas que respondan a necesidades locales." },
      bottom: "La academia abre la puerta; el coworking ofrece el siguiente lugar para construir.",
    },
    grants: {
      title: "Retos locales y oportunidades de empleo.",
      need: { title: "Grants para retos locales", body: "Negocios y organizaciones identifican problemas para que estudiantes y emprendedores desarrollen soluciones.", note: "Capital sujeto a acuerdos con financiadores." },
      teams: { title: "Puente al empleo", body: "Egresados pueden postularse a prácticas, co-ops y vacantes en empresas del hub o aliadas.", note: "La contratación depende de cada empresa." },
      bottom: "Dos caminos para aplicar lo aprendido: crear una solución o integrarse a un equipo.",
    },
    residencies: {
      title: "Perspectivas globales, trabajo local.",
      invited: { title: "Fundadores invitados", body: "Emprendedores de otras ciudades y países llegan por invitación o convocatoria para integrarse al hub." },
      exchange: { title: "Intercambio cotidiano", body: "Trabajan junto a equipos locales y comparten métodos, cultura y redes que amplían lo que parece posible." },
      bottom: "Relaciones duraderas entre la comunidad local y una red internacional.",
    },
    events: {
      title: "Eventos que conectan Utopías con el mundo tecnológico.",
      community: "miembros de AI Builders México",
      cadence: "Encuentros mensuales, charlas y talleres abiertos a la comunidad.",
      partnerLabel: "Nuestra red de aliados",
      partnerIntro: "Podemos invitar a integrantes de sus equipos a compartir experiencia en Utopías, según agenda y acuerdos.",
    },
    space: {
      category: "El espacio", title: "Que se sienta como una posibilidad nueva.",
      statement: "Un espacio que invite al asombro, al intercambio y a crear algo más grande que uno mismo.",
      images: [
        { src: "/deck/space-coworking.avif", caption: "Trabajo compartido", alt: "Referencia conceptual de mesas de coworking y gradas" },
        { src: "/deck/space-projects.avif", caption: "Aprendizaje entre pares", alt: "Referencia conceptual de grupos trabajando en mesas de proyecto" },
        { src: "/deck/space-events.avif", caption: "Encuentros y talleres", alt: "Referencia conceptual de un espacio abierto para charlas y talleres" },
      ],
      note: "Referencias conceptuales; diseño final por definir.",
    },
    budget: {
      category: "Presupuesto de lanzamiento", title: "US$50,000 para ponerlo en marcha.",
      intro: "Propuesta de honorarios para el equipo mexicano que está creando el currículo, la identidad, el espacio y la operación inicial.",
      areas: ["Currículo y plataforma", "Marca, web y diseño espacial", "Operación de cohorte y comunidad", "Producción y seguimiento"],
      note: "Áreas de inversión propuestas. Obra, mobiliario y capital para grants requieren acuerdos o recursos adicionales.",
    },
    plan: {
      category: "Plan y metas", title: "Una primera cohorte. Un hub de largo plazo.",
      school: {
        label: "Academia · primera cohorte",
        metrics: [{ value: "150", label: "estudiantes" }, { value: "12", label: "semanas" }],
        note: "El currículo abierto sigue disponible y permite nuevas cohortes.",
      },
      hub: {
        label: "Hub · metas propuestas para 12 meses",
        metrics: [
          { value: "20", label: "equipos activos en coworking" },
          { value: "4", label: "residencias de emprendedores" },
          { value: "4", label: "retos locales" },
          { value: "12", label: "eventos abiertos" },
        ],
        note: "Convocatorias continuas, independientes de la cohorte.",
      },
      milestones: [
        { date: "OCT–DIC 2026", label: "Preparación y convocatoria" },
        { date: "ENE 2027", label: "Apertura del hub y la cohorte" },
        { date: "ABR 2027", label: "Primera muestra de proyectos" },
        { date: "CONTINUO", label: "Coworking, residencias, retos y eventos" },
      ],
      note: "Metas indicativas, sujetas a capacidad del espacio, equipo y financiamiento de grants.",
    },
    close: {
      eyebrow: "Iquiti · Coyoacán, Ciudad de México",
      title: "Construyamos el", emphasis: "siguiente nodo.",
      lead: "Un punto de partida para que el talento local cree soluciones, trayectorias profesionales y empresas con tecnología.",
    },
  },
  en: {
    ui: {
      deck: "Iquiti presentation",
      location: "Innovation Hub · Mexico City",
      language: "Switch to Spanish",
      overview: "Overview",
      overviewAria: "Show slide overview",
      overviewNav: "Go to a slide",
      pillarNav: "Explore Iquiti's five parts",
      slide: "slide",
      of: "of",
      previous: "Previous slide",
      next: "Next slide",
    },
    slides: [
      { label: "Opening", title: "Mexico City's innovation hub." },
      { label: "The problem", title: "The talent is here. The path to building with technology is fragmented." },
      { label: "Reinvestment", title: "A cycle that expands opportunity across Mexico City." },
      { label: "Our thesis", title: "Innovation begins when more people can create." },
      { label: "The Hub", title: "One ecosystem, five engines." },
      { label: "01 · Academy", title: "Learn how to learn. Learn by building." },
      { label: "02 · Coworking", title: "A place to build companies with the community." },
      { label: "03 · Grants & talent", title: "Local challenges and career opportunities." },
      { label: "04 · Residencies", title: "Global perspective, local work." },
      { label: "05 · Events", title: "Events connecting Utopías to the tech world." },
      { label: "The space", title: "A place that feels like a new possibility." },
      { label: "Budget", title: "US$50,000 to launch it." },
      { label: "Plan & targets", title: "A first cohort. A hub built to last." },
      { label: "Closing", title: "Let's build the next node." },
    ],
    cover: {
      eyebrow: "Iquiti · Innovation Hub and Technology Academy",
      title: "Mexico City's",
      emphasis: "innovation hub.",
      lead: "The next company could start here.",
    },
    problem: {
      category: "The problem", title: "The talent is here. The path to building with technology is fragmented.",
      points: [
        { title: "The technical skills gap is widening", body: "As AI expands what skilled builders can achieve, access to the learning and practice needed to build with it is not keeping pace." },
        { title: "The leap from ideas to impact", body: "That leap needs projects, peers, physical space, and support. Without them, ideas rarely become useful solutions or growing companies." },
        { title: "A place to dream", body: "Local talent needs a nearby hub where global founders, ideas, and cultures expand what feels possible." },
      ],
      bottom: "The result: ideas without a clear path to jobs, companies, or local reinvestment.",
    },
    reinvestment: {
      category: "Reinvestment cycle", title: "A cycle that expands opportunity across Mexico City.",
      steps: [
        { title: "Open learning", body: "People learn to use AI and technology to build products and businesses, at their own pace and with peers." },
        { title: "Projects in the hub", body: "Coworking, challenges, and resident founders help turn those skills into real solutions." },
        { title: "Jobs and ventures", body: "Graduates can join hub companies or partner employers; new teams can also hire locally." },
        { title: "Reinvestment", body: "Growing companies can hire and train others. A liquidity event could help fund the next generation." },
      ],
      bottom: "Talent, companies, and capital can flow back into Mexico City's ecosystem, cycle after cycle.",
    },
    thesis: {
      category: "Opportunity & thesis", title: "Innovation begins when more people can create.",
      statement: "An open school and a hub in one place turn technical ability into projects, careers, and companies rooted in Coyoacán.",
      points: [
        { title: "Open school", body: "Free, self-directed, and peer-led; an open-source curriculum and a first in-person cohort of 150 people over 12 weeks." },
        { title: "Innovation hub", body: "Coworking, challenges, residencies, and events where learners apply their skills alongside entrepreneurs." },
      ],
    },
    hub: {
      category: "Innovation Hub", title: "One ecosystem, five engines.",
      pillars: [
        { title: "Academy", body: "A free, open-source school built around peer learning and weekly projects." },
        { title: "Coworking", body: "A free home for selected entrepreneurs and graduates." },
        { title: "Grants & talent", body: "Local challenges and paths to internships or jobs with hub companies and talent partners." },
        { title: "Residencies", body: "Entrepreneurs from other cities and countries who come to exchange knowledge." },
        { title: "Events", body: "Monthly gatherings and workshops with voices from our technology partner network." },
      ],
    },
    academy: {
      title: "Learn how to learn. Learn by building.",
      promise: "Free. Open source. In person and online.", distinction: "Peer-led, with no lectures.",
      points: [
        { title: "Method", body: "Self-directed learning, problem solving, and support from peers." },
        { title: "Structure", body: "An open curriculum, accountability, and projects every week." },
        { title: "Next step", body: "A portfolio for internships, co-ops, or jobs; projects that can continue in the hub." },
      ],
      bottom: "First cohort: 150 students and 12 weeks to build together.",
    },
    coworking: {
      title: "A place to build companies with the community.",
      entry: { title: "Free access", body: "Graduates and local entrepreneurs can apply for workspace at Iquiti to develop their projects." },
      next: { title: "Room to keep building", body: "Teams find peers and feedback to turn prototypes into companies that address local needs." },
      bottom: "The Academy opens the door; coworking offers the next place to build.",
    },
    grants: {
      title: "Local challenges and career opportunities.",
      need: { title: "Grants for local challenges", body: "Businesses and organizations identify problems for students and entrepreneurs to solve.", note: "Capital depends on funding agreements." },
      teams: { title: "Path to employment", body: "Graduates can apply for internships, co-ops, and jobs with hub companies or partner employers.", note: "Each company makes its own hiring decisions." },
      bottom: "Two ways to apply new skills: build a solution or join a team.",
    },
    residencies: {
      title: "Global perspective, local work.",
      invited: { title: "Invited founders", body: "Entrepreneurs from other cities and countries join the hub by invitation or application." },
      exchange: { title: "Everyday exchange", body: "They work alongside local teams and share methods, culture, and networks that widen what seems possible." },
      bottom: "Lasting relationships between the local community and an international network.",
    },
    events: {
      title: "Events connecting Utopías to the tech world.",
      community: "AI Builders México members",
      cadence: "Monthly gatherings, talks, and workshops open to the community.",
      partnerLabel: "Our partner network",
      partnerIntro: "We can invite people from their teams to share experience at Utopías, subject to schedules and agreements.",
    },
    space: {
      category: "The space", title: "A place that feels like a new possibility.",
      statement: "A space that invites wonder, exchange, and the creation of something bigger than any one person.",
      images: [
        { src: "/deck/space-coworking.avif", caption: "Shared workspace", alt: "Concept reference of coworking tables and stepped seating" },
        { src: "/deck/space-projects.avif", caption: "Peer learning", alt: "Concept reference of groups working around project tables" },
        { src: "/deck/space-events.avif", caption: "Gatherings and workshops", alt: "Concept reference of an open space for talks and workshops" },
      ],
      note: "Concept references; final design to be determined.",
    },
    budget: {
      category: "Launch budget", title: "US$50,000 to launch it.",
      intro: "Proposed compensation for the Mexican team creating the curriculum, identity, space, and initial operations.",
      areas: ["Curriculum and platform", "Brand, website, and space design", "Cohort and community operations", "Production and measurement"],
      note: "Proposed uses of funds. Construction, furniture, and grant capital require additional agreements or resources.",
    },
    plan: {
      category: "Plan & targets", title: "A first cohort. A hub built to last.",
      school: {
        label: "Academy · first cohort",
        metrics: [{ value: "150", label: "students" }, { value: "12", label: "weeks" }],
        note: "The open curriculum stays available and supports future cohorts.",
      },
      hub: {
        label: "Hub · proposed 12-month targets",
        metrics: [
          { value: "20", label: "active coworking teams" },
          { value: "4", label: "entrepreneur residencies" },
          { value: "4", label: "local challenges" },
          { value: "12", label: "open events" },
        ],
        note: "Rolling applications, independent of the cohort.",
      },
      milestones: [
        { date: "OCT–DEC 2026", label: "Prepare and recruit" },
        { date: "JAN 2027", label: "Open the hub and cohort" },
        { date: "APR 2027", label: "First project showcase" },
        { date: "ONGOING", label: "Coworking, residencies, challenges, events" },
      ],
      note: "Indicative targets, subject to space capacity, staffing, and grant funding.",
    },
    close: {
      eyebrow: "Iquiti · Coyoacán, Mexico City",
      title: "Let's build the", emphasis: "next node.",
      lead: "A starting point for local talent to create solutions, careers, and companies with technology.",
    },
  },
} as const;

export type DeckLanguage = keyof typeof deckCopy;
